export enum ProjectActions {
  FETCH_USER_PROJECTS = "PROJECTS/FETCH_USER_PROJECTS",
  FETCH_USER_PROJECTS_SUCCESS = "PROJECTS/FETCH_USER_PROJECTS_SUCCESS",
  FETCH_USER_PROJECTS_FAILURE = "PROJECTS/FETCH_USER_PROJECTS_FAILURE",
  ADD_PROJECT = "PROJECTS/ADD_PROJECT",
  ADD_PROJECT_SUCCESS = "PROJECTS/ADD_PROJECT_SUCCESS",
  ADD_PROJECT_FAILURE = "PROJECTS/ADD_PROJECT_FAILURE",
  FETCH_USER_PROJECT = "PROJECTS/FETCH_USER_PROJECT",
  FETCH_USER_PROJECT_SUCCESS = "PROJECTS/FETCH_USER_PROJECT_SUCCESS",
  FETCH_USER_PROJECT_FAILURE = "PROJECTS/FETCH_USER_PROJECT_FAILURE",
  FETCH_PROJECT_COLORS = "PROJECTS/FETCH_PROJECT_COLORS",
  FETCH_PROJECT_COLORS_SUCCESS = "PROJECTS/FETCH_PROJECT_COLORS_SUCCESS",
  FETCH_PROJECT_COLORS_FAILURE = "PROJECTS/FETCH_PROJECT_COLORS_FAILURE"
}
