export enum ProjectActions {
  FETCH_USER_PROJECTS = "USERS/FETCH_USER_PROJECTS",
  FETCH_USER_PROJECTS_SUCCESS = "USERS/FETCH_USER_PROJECTS_SUCCESS",
  FETCH_USER_PROJECTS_FAILURE = "USERS/FETCH_USER_PROJECTS_FAILURE"
}
