export enum UserActions {
  CREATE_USER = "USERS/CREATE_USER",
  CREATE_USER_SUCCESS = "USERS/CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE = "USERS/CREATE_USER_FAILURE",
  AUTHENTICATE_USER = "USERS/AUTHENTICATE_USER",
  AUTHENTICATE_USER_SUCCESS = "USERS/AUTHENTICATE_USER_SUCCESS",
  AUTHENTICATE_USER_FAILURE = "USERS/AUTHENTICATE_USER_FAILURE"
}
