export enum TaskActions {
  FETCH_PROJECT_TASKS = "TASKS/FETCH_PROJECT_TASKS",
  FETCH_PROJECT_TASKS_SUCCESS = "TASKS/FETCH_PROJECT_TASKS_SUCCESS",
  FETCH_PROJECT_TASKS_FAILURE = "TASKS/FETCH_PROJECT_TASKS_FAILURE"
}
